### PR TITLE
Add preferences to Firefox extension

### PR DESCRIPTION
**Pull request by T0astBread**
This enables the preferences UI in Firefox.

I really just copied the necessary files over from the Chrome ext (verbatim) and adjusted the manifest slightly.

### CODE REVIEW

**Comment by thomaswangio** [comment]
Thanks @T0astBread!

**Comment by thomaswangio** [comment]
Added this to Firefox store, should be up shortly! (they're much faster than Chrome) @T0astBread

**Comment by thomaswangio** [comment]
Approved in less than 2 minutes! Vs. Chrome has been pending for more than a day @T0astBread https://addons.mozilla.org/en-US/firefox/addon/min-twitter/

**Comment by T0astBread** [comment]
Wonderful!

**Pull request merged**
